# Generated by Django 4.2.7 on 2023-11-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='sex',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
