# Generated by Django 4.2.7 on 2023-11-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='location',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
