# Generated by Django 4.2.7 on 2023-11-20 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_time',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout_time',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
