# Generated by Django 4.2.7 on 2023-11-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_booking_time_booking_checkin_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dest',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
